In [1]:
import numpy as np
import pandas as pd

In [16]:
# a.	Generate a two-dimensional integer array with the shape of (20,5) and name its “data”.
#     Fill “data” with random integers from -100 to 100.
#     Display “data” at the end.

data = np.random.randint(-100,100,(20,5))
data

array([[  52,    8,  -95,  -30,  -89],
       [   0,   17,   88,   24,  -34],
       [ -27,  -97,   15,  -30,   76],
       [ -27,   17,  -68,    3,  -42],
       [ -61,  -15,  -89,   64,  -72],
       [  82,   14,   -6,   12,  -14],
       [  85,  -16,  -95,  -24,  -24],
       [ -95,  -75,   70,   61,  -70],
       [  63,  -44,  -53,   48,   49],
       [ -31,  -90,    1,  -39,   75],
       [ -25,    7,  -29,    7,  -32],
       [ -57,   24,   42,   71,   82],
       [  92,  -16,  -43,  -15,   53],
       [ -85,  -90,   74,  -97,   90],
       [ -55,  -93,   74,   -7,   63],
       [  78,   56,  -48,   80,   23],
       [-100,   76,  -78,   61,  -79],
       [ -72,  -82,    6,   95,   43],
       [ -49,  -43,   88,   79,   -7],
       [  48,  -17,   32,   94,  -72]])

In [17]:
# b.	Display the average value of the third column in “data”.
data[:,2].mean()


-5.7

In [19]:
# c.	Display the average value of the first 5 rows in “data”.
data[:5,:].mean()


-16.48

In [20]:
# d.	Display the average value of the first 3 rows and the 4th column in “data”.
data[:3,3].mean()


-12.0

In [21]:
# e.	Create a new NumPy array which contains the last 4 elements of the second row of “data”.  Display the new array at the end.
new_np_array = data[1,1:]
new_np_array


array([ 17,  88,  24, -34])

In [22]:
# f.	Reshape “data” int to 10 x 10 matrix.  Display the matrix at the end.
data_reshaped = data.reshape(10, 10)
data_reshaped


array([[  52,    8,  -95,  -30,  -89,    0,   17,   88,   24,  -34],
       [ -27,  -97,   15,  -30,   76,  -27,   17,  -68,    3,  -42],
       [ -61,  -15,  -89,   64,  -72,   82,   14,   -6,   12,  -14],
       [  85,  -16,  -95,  -24,  -24,  -95,  -75,   70,   61,  -70],
       [  63,  -44,  -53,   48,   49,  -31,  -90,    1,  -39,   75],
       [ -25,    7,  -29,    7,  -32,  -57,   24,   42,   71,   82],
       [  92,  -16,  -43,  -15,   53,  -85,  -90,   74,  -97,   90],
       [ -55,  -93,   74,   -7,   63,   78,   56,  -48,   80,   23],
       [-100,   76,  -78,   61,  -79,  -72,  -82,    6,   95,   43],
       [ -49,  -43,   88,   79,   -7,   48,  -17,   32,   94,  -72]])

In [23]:
# g.	Calculate the std deviation of “data”.
data_reshaped.std()


59.998282475417575

In [24]:
# h.	Replace the largest number of each row in “data” with the average of the corresponding row.  Display “data” at the end.

# Calculate the average of each row
row_averages = np.mean(data_reshaped, axis=1)

# Find the index of the maximum value in each row
max_indices = np.argmax(data_reshaped, axis=1)

# Replace the maximum values with the row averages
data_reshaped[np.arange(data_reshaped.shape[0]), max_indices] = row_averages

data_reshaped

array([[  52,    8,  -95,  -30,  -89,    0,   17,   -5,   24,  -34],
       [ -27,  -97,   15,  -30,  -18,  -27,   17,  -68,    3,  -42],
       [ -61,  -15,  -89,   64,  -72,   -8,   14,   -6,   12,  -14],
       [ -18,  -16,  -95,  -24,  -24,  -95,  -75,   70,   61,  -70],
       [  63,  -44,  -53,   48,   49,  -31,  -90,    1,  -39,   -2],
       [ -25,    7,  -29,    7,  -32,  -57,   24,   42,   71,    9],
       [  -3,  -16,  -43,  -15,   53,  -85,  -90,   74,  -97,   90],
       [ -55,  -93,   74,   -7,   63,   78,   56,  -48,   17,   23],
       [-100,   76,  -78,   61,  -79,  -72,  -82,    6,  -13,   43],
       [ -49,  -43,   88,   79,   -7,   48,  -17,   32,   15,  -72]])

In [26]:
# i.	Create a new NumPy array which contains random 2 rows in “data”.  Display the new array at the end.
new_array_2 = data_reshaped[np.random.choice(data_reshaped.shape[0], size=2, replace=False)]
new_array_2


array([[ 63, -44, -53,  48,  49, -31, -90,   1, -39,  -2],
       [-25,   7, -29,   7, -32, -57,  24,  42,  71,   9]])

In [27]:
# j.	Create a new NumPy array which contains random 3 columns in “data”.  Display the new array at the end.
new_array_3 = data_reshaped[:, np.random.choice(data_reshaped.shape[1], size=3, replace=False)]
new_array_3


array([[-89,   0,   8],
       [-18, -27, -97],
       [-72,  -8, -15],
       [-24, -95, -16],
       [ 49, -31, -44],
       [-32, -57,   7],
       [ 53, -85, -16],
       [ 63,  78, -93],
       [-79, -72,  76],
       [ -7,  48, -43]])

In [28]:
# k.	Create a new NumPy array which contains 100 random doubles drawn from a normal (Gaussian) distribution.  Display the new array at the end.
new_array_4 = np.random.randn(100)
new_array_4


array([-0.98155764, -1.2562432 , -2.09840774,  0.51982884,  1.71891157,
       -0.05345565,  0.45040225,  2.09350098,  1.00981126,  2.58086935,
       -0.80622077,  1.05902436,  1.67569729, -0.52007447,  1.79986606,
       -1.13417974,  0.24770548, -1.438189  , -0.39844736, -1.05646879,
        1.50255125,  0.0641152 ,  0.18847731,  1.3612447 ,  0.0372142 ,
        0.46833839, -0.4524396 , -0.14607953, -0.32153184, -0.28436803,
       -0.34741718,  1.16829536, -0.18656785,  0.34499741, -0.30692009,
        1.54935293, -0.38750084,  0.42581375,  1.09427799,  0.31575858,
        0.22880723, -1.14573825,  2.10209137, -1.56956331,  1.47416237,
        0.94152399, -1.02535707, -1.85335645,  0.6039452 , -0.18173249,
        0.99235404, -0.34605419, -0.17336287, -0.30434745, -0.0572594 ,
        1.2343876 , -0.67534335,  0.60921094, -0.08011159, -2.047126  ,
       -0.74257201, -0.74212094, -0.67848742,  2.33106698, -0.48940026,
       -1.16055229,  1.13252511, -1.86144634, -0.74359123,  0.85

In [30]:
# l.	Convert the "data" to a Pandas Data Frame with the header “a” – “e” and name it “dataframe”. Describe the “dataframe” at the end.
dataframe = pd.DataFrame(data, columns=['a', 'b', 'c', 'd', 'e'])
dataframe.describe()


a         b          c          d          e
count   20.000000  20.00000  20.000000  20.000000  20.000000
mean   -23.600000 -22.95000 -10.350000  10.350000 -11.250000
std     51.907205  51.94073  60.282908  44.734627  52.178716
min   -100.000000 -97.00000 -95.000000 -97.000000 -89.000000
25%    -58.000000 -76.75000 -56.750000 -17.250000 -49.000000
50%    -27.000000 -16.00000  -5.500000   9.500000 -16.000000
75%     -2.250000  14.75000  34.500000  51.250000  28.000000
max     78.000000  76.00000  88.000000  79.000000  90.000000

In [31]:
# m.	Save the “dataframe” into assign1.xlsx.
dataframe.to_excel('assign1.xlsx', index=False)


In [32]:
# n.	Save the “dataframe” into assign1.csv.
dataframe.to_csv('assign1.csv', index=False)


In [33]:
# o.	Replace all the negative numbers in “dataframe” to 0. Describe the “dataframe” at the end.
dataframe[dataframe < 0] = 0
dataframe.describe()


a          b          c          d          e
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   12.050000  10.950000  20.100000  23.100000  16.500000
std    25.295048  20.489985  31.259356  28.785779  27.427416
min     0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.000000   0.000000   0.000000   0.000000   0.000000
50%     0.000000   0.000000   0.000000   9.500000   0.000000
75%     0.000000  14.750000  34.500000  51.250000  28.000000
max    78.000000  76.000000  88.000000  79.000000  90.000000

In [34]:
# p.	Replace all the zeros in the “dataframe” to 1. Describe the “dataframe” at the end.
dataframe[dataframe == 0] = 1
dataframe.describe()


a          b          c          d        e
count  20.000000  20.000000  20.000000  20.000000  20.0000
mean   12.850000  11.550000  20.650000  23.500000  17.1500
std    24.894039  20.155905  30.889063  28.450326  27.0171
min     1.000000   1.000000   1.000000   1.000000   1.0000
25%     1.000000   1.000000   1.000000   1.000000   1.0000
50%     1.000000   1.000000   1.000000   9.500000   1.0000
75%     1.000000  14.750000  34.500000  51.250000  28.0000
max    78.000000  76.000000  88.000000  79.000000  90.0000